### PR TITLE
Add support for shared builds on windows

### PR DESCRIPTION
**Pull request by thesn10**
In this PR i have added support for shared linking on windows.
This is helpful if you need seperate `.dll` files, for example `avformat.dll` or other libraries

You can append `-shared` to the version to enable it:
```yaml
with:
  ffmpeg-version: '5.1.1-shared'
  # or
  ffmpeg-version: 'release-shared'
```

This will make it download the shared build with seperate `.dll` files like this:
```
> dir C:\hostedtoolcache\windows\ffmpeg\6.1.1\x64

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          12/31/2023  8:23 AM       79826944 avcodec-60.dll
-a---          12/31/2023  8:23 AM        4417024 avdevice-60.dll
-a---          12/31/2023  8:23 AM       39759872 avfilter-9.dll
-a---          12/31/2023  8:23 AM       17132544 avformat-60.dll
-a---          12/31/2023  8:23 AM        2302976 avutil-58.dll
-a---          12/31/2023  8:23 AM         388608 ffmpeg.exe
-a---          12/31/2023  8:23 AM        1875968 ffplay.exe
-a---          12/31/2023  8:23 AM         192000 ffprobe.exe
-a---          12/31/2023  8:23 AM          76288 postproc-57.dll
-a---          12/31/2023  8:23 AM         436224 swresample-4.dll
-a---          12/31/2023  8:23 AM         643072 swscale-7.dll
```

### CODE REVIEW

**Comment by FedericoCarboni** [comment]
Instead of adding a suffix to `ffmpeg-version` I'd rather use a new input (something like `linking` which could be `static` or `shared`) and error out when set to `shared` on macos or linux. The functionality itself looks good though :+1:

**Comment by thesn10** [comment]
Yes that is a good idea, i'm going to implement it

**Comment by thesn10** [comment]
I have added the `linking-type` option

**Comment by FedericoCarboni** [comment]
Everything looks good :+1:

**Pull request merged**
